[package]
name = "tvm-cli-rs"
version = "0.1.0"
authors = ["Jared Roesch <jroesch@octoml.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
tvm = { path = "tvm/rust/tvm" }
anyhow = "1.0"
